version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: v3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gorima
      MYSQL_PASSWORD: gorima
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./server
    restart: always
    container_name: backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Montage du volume des certificats dans le container pour que Nginx puisse y accéder
      - certs:/etc/letsencrypt
      # Montage du volume pour le challenge ACME (doit correspondre à la racine définie dans nginx.conf)
      - certbot-webroot:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email juba.belhocine@outlook.fr --agree-tos --no-eff-email -d miniforum.jubabelhocine.com
    # Vous pouvez lancer ce service manuellement pour obtenir le certificat, puis l'arrêter

volumes:
  db_data:
  certs:
  certbot-webroot:

networks:
  app-network:
    driver: bridge
