version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: i0am6x4xu6o9c87l
      MYSQL_ROOT_PASSWORD: mlgk36psaklp3oidmlgk36psaklp3oidi0am6x4xu6o9c87l
      MYSQL_USER: n0fvn1lt5ug68fn3
      MYSQL_PASSWORD: mlgk36psaklp3oid
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./server
    restart: always
    container_name: backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - app-network


volumes:
  db_data:


networks:
  app-network:
    driver: bridge
